-- CreateTable users
CREATE TABLE "users" (
    "USR_ID" SERIAL NOT NULL PRIMARY KEY,
    "USR_NOME" VARCHAR(100) NOT NULL,
    "USR_EMAIL" VARCHAR(255) NOT NULL UNIQUE,
    "USR_SENHA" VARCHAR(255) NOT NULL,
    "USR_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USR_UPDATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable tasks
CREATE TABLE "tasks" (
    "TSK_ID" SERIAL NOT NULL PRIMARY KEY,
    "TSK_TITULO" VARCHAR(200) NOT NULL,
    "TSK_DESCRICAO" TEXT,
    "TSK_STATUS" VARCHAR(20) NOT NULL DEFAULT 'pendente',
    "TSK_USR_ID" INTEGER NOT NULL,
    "TSK_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TSK_UPDATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "tasks_TSK_USR_ID_fkey" FOREIGN KEY ("TSK_USR_ID") REFERENCES "users" ("USR_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable logs
CREATE TABLE "logs" (
    "LOG_ID" SERIAL NOT NULL PRIMARY KEY,
    "LOG_LEVEL" VARCHAR(20) NOT NULL,
    "LOG_MESSAGE" TEXT NOT NULL,
    "LOG_METADATA" JSONB,
    "LOG_TIMESTAMP" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateIndex para busca rápida por nível de erro
CREATE INDEX "logs_LOG_LEVEL_idx" ON "logs"("LOG_LEVEL");

-- CreateIndex para buscas por data (útil para auditoria)
CREATE INDEX "logs_LOG_TIMESTAMP_idx" ON "logs"("LOG_TIMESTAMP");

-- CreateIndex
CREATE INDEX "tasks_TSK_USR_ID_idx" ON "tasks"("TSK_USR_ID");

-- CreateIndex
CREATE INDEX "tasks_TSK_USR_ID_TSK_STATUS_idx" ON "tasks"("TSK_USR_ID", "TSK_STATUS");
