-- CreateTable users
CREATE TABLE "users" (
    "USR_ID" SERIAL NOT NULL PRIMARY KEY,
    "USR_NOME" VARCHAR(100) NOT NULL,
    "USR_EMAIL" VARCHAR(255) NOT NULL UNIQUE,
    "USR_SENHA" VARCHAR(255) NOT NULL,
    "USR_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "USR_UPDATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable tasks
CREATE TABLE "tasks" (
    "TSK_ID" SERIAL NOT NULL PRIMARY KEY,
    "TSK_TITULO" VARCHAR(200) NOT NULL,
    "TSK_DESCRICAO" TEXT,
    "TSK_STATUS" VARCHAR(20) NOT NULL DEFAULT 'pendente',
    "TSK_USR_ID" INTEGER NOT NULL,
    "TSK_CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TSK_UPDATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "tasks_TSK_USR_ID_fkey" FOREIGN KEY ("TSK_USR_ID") REFERENCES "users" ("USR_ID") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE INDEX "tasks_TSK_USR_ID_idx" ON "tasks"("TSK_USR_ID");

-- CreateIndex
CREATE INDEX "tasks_TSK_USR_ID_TSK_STATUS_idx" ON "tasks"("TSK_USR_ID", "TSK_STATUS");
